name: Docker Image CI

on:
  push:
    branches: [ "mastermind" ]
  pull_request:
    branches: [ "mastermind" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: satcon
    steps:
    - uses: actions/checkout@v3
    - name: Set working directory
      run: cd /home/miro/docker-tomcat
    - name: Stop old satcon
      run: bash /home/miro/docker-tomcat/stop_satcon.sh
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag satcon
    - name: Run the containers with satcon
      run: docker run -d -p 80:8080 satcon
